const SET_ARTICLES = 'SET_ARTICLES';
const ADD_ARTICLE = 'ADD_ARTICLE';
const EDIT_ARTICLE = 'EDIT_ARTICLE';
const DELETE_ARTICLE = 'DELETE_ARTICLE';

export { SET_ARTICLES, ADD_ARTICLE, EDIT_ARTICLE, DELETE_ARTICLE };
